### ISSUE TITLE
exercise 33 is broken

### ISSUE THREAD

**Issue by tadjik1** [ReactiveX/learnrx#64]
there is a problem with contactPoint event object — there are no offsetX and offsetY properties.

**Comment by krivulcik** [comment]
This is the case only in firefox. I got affected by this too, but it works correctly in Chromium.
This seems to be not easily fixable:
http://stackoverflow.com/questions/12704686/html5-with-jquery-e-offsetx-is-undefined-in-firefox
http://stackoverflow.com/questions/11334452/event-offsetx-in-firefox

**Comment by peteruithoven** [comment]
Also see: http://www.quirksmode.org/js/events_properties.html#position

**Comment by gabrielkunkel** [comment]
I'm using Chrome and the results of exercise 33 is no different than exercise 32. No matter where the contact point is, the sprint still places itself so the mouse arrow is at the top left-hand corner. I clicked "Show Answer" before I ran it.

Is this a different issue? Am I the only one experiencing this?

**Comment by varungupta85** [comment]
@gabrielkunkel I see the issue on Firefox but not on Chrome. You may want to refresh the page and run the exercise again in Chrome to discard any stale state in the application.

**Comment by mjomble** [comment]
@gabrielkunkel PR #130 has a fix for that

**Comment by morenoh149** [comment]
fixed by https://github.com/ReactiveX/learnrx/pull/130

**Comment by mjomble** [comment]
It is possible the original problem is still unresolved, #130 only fixed the issue later mentioned by @gabrielkunkel

**Comment by thomasvanlankveld** [comment]
When I run the answer (in chrome), the sprite disappears from the screen if I drag it
